// Syphax-Engine - Ougi Washi

#include "se_gl.h"
#include <stdio.h>
#include <stdlib.h>

PFNGLDELETEBUFFERS glDeleteBuffers = NULL;
PFNGLGENBUFFERS glGenBuffers = NULL;
PFNGLBINDBUFFER glBindBuffer = NULL;
PFNGLBUFFERSUBDATA glBufferSubData = NULL;
PFNGLBUFFERDATA glBufferData = NULL;
PFNGLUSEPROGRAM glUseProgram = NULL;
PFNGLCREATESHADER glCreateShader = NULL;
PFNGLSHADERSOURCE glShaderSource = NULL;
PFNGLCOMPILESHADER glCompileShader = NULL;
PFNGLCREATEPROGRAM glCreateProgram = NULL;
PFNGLLINKPROGRAM glLinkProgram = NULL;
PFNGLATTACHSHADER glAttachShader = NULL;
PFNGLDELETEPROGRAM glDeleteProgram = NULL;
PFNGLDELETESHADER glDeleteShader = NULL;
PFNGLGENRENDERBUFFERS glGenRenderbuffers = NULL;
PFNGLBINDFRAMEBUFFER glBindFramebuffer = NULL;
PFNGLFRAMEBUFFERRENDERBUFFER glFramebufferRenderbuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE glFramebufferTexture = NULL;
PFNGLBINDVERTEXARRAY glBindVertexArray = NULL;
PFNGLGENVERTEXARRAYS glGenVertexArrays = NULL;
PFNGLDELETEVERTEXARRAYS glDeleteVertexArrays = NULL;
PFNGLVERTEXATTRIBPOINTER glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAY glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAY glDisableVertexAttribArray = NULL;
PFNGLVERTEXATTRIBDIVISOR glVertexAttribDivisor = NULL;
PFNGLDRAWARRAYSINSTANCED glDrawArraysInstanced = NULL;
PFNGLGENFRAMEBUFFERS glGenFramebuffers = NULL;
PFNGLFRAMEBUFFERTEXTURE2D glFramebufferTexture2D = NULL;
PFNGLGETSHADERIV glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOG glGetShaderInfoLog = NULL;
PFNGLGETPROGRAMIV glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOG glGetProgramInfoLog = NULL;
PFNGLDRAWELEMENTSINSTANCED glDrawElementsInstanced = NULL;
PFNGLMAPBUFFER glMapBuffer = NULL;
PFNGLUNMAPBUFFER glUnmapBuffer = NULL;
PFNGLGETUNIFORMLOCATION glGetUniformLocation = NULL;
PFNGLUNIFORM1I glUniform1i = NULL;
PFNGLUNIFORM1F glUniform1f = NULL;
PFNGLUNIFORM1FV glUniform1fv = NULL;
PFNGLUNIFORM2FV glUniform2fv = NULL;
PFNGLUNIFORM3FV glUniform3fv = NULL;
PFNGLUNIFORM4FV glUniform4fv = NULL;
PFNGLUNIFORM1IV glUniform1iv = NULL;
PFNGLUNIFORM2IV glUniform2iv = NULL;
PFNGLUNIFORM3IV glUniform3iv = NULL;
PFNGLUNIFORM4IV glUniform4iv = NULL;
PFNGLUNIFORMMATRIX3FV glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FV glUniformMatrix4fv = NULL;
PFNGLBINDRENDERBUFFER glBindRenderbuffer = NULL;
PFNGLDELETERENDERBUFFERS glDeleteRenderbuffers = NULL;
PFNGLDELETEFRAMEBUFFERS glDeleteFramebuffers = NULL;
PFNGLRENDERBUFFERSTORAGE glRenderbufferStorage = NULL;
PFNGLCHECKFRAMEBUFFERSTATUS glCheckFramebufferStatus = NULL;
PFNGLGENERATEMIPMAP glGenerateMipmap = NULL;
PFNGLBLITFRAMEBUFFER glBlitFramebuffer = NULL;

#define INIT_OPENGL_FUNCTION(func, func_type)									\
	func = (func_type)glfwGetProcAddress(#func);								 \
	if (!func) {																 \
	fprintf(stderr, "Failed to load OpenGL function: %s\n", #func);			\
	exit(1);																	 \
	}

void se_init_opengl() {
	INIT_OPENGL_FUNCTION(glDeleteBuffers, PFNGLDELETEBUFFERS);
	INIT_OPENGL_FUNCTION(glGenBuffers, PFNGLGENBUFFERS);
	INIT_OPENGL_FUNCTION(glBindBuffer, PFNGLBINDBUFFER);
	INIT_OPENGL_FUNCTION(glBufferSubData, PFNGLBUFFERSUBDATA);
	INIT_OPENGL_FUNCTION(glBufferData, PFNGLBUFFERDATA);
	INIT_OPENGL_FUNCTION(glUseProgram, PFNGLUSEPROGRAM);
	INIT_OPENGL_FUNCTION(glCreateShader, PFNGLCREATESHADER);
	INIT_OPENGL_FUNCTION(glShaderSource, PFNGLSHADERSOURCE);
	INIT_OPENGL_FUNCTION(glCompileShader, PFNGLCOMPILESHADER);
	INIT_OPENGL_FUNCTION(glCreateProgram, PFNGLCREATEPROGRAM);
	INIT_OPENGL_FUNCTION(glLinkProgram, PFNGLLINKPROGRAM);
	INIT_OPENGL_FUNCTION(glAttachShader, PFNGLATTACHSHADER);
	INIT_OPENGL_FUNCTION(glDeleteProgram, PFNGLDELETEPROGRAM);
	INIT_OPENGL_FUNCTION(glDeleteShader, PFNGLDELETESHADER);
	INIT_OPENGL_FUNCTION(glGenRenderbuffers, PFNGLGENRENDERBUFFERS);
	INIT_OPENGL_FUNCTION(glBindFramebuffer, PFNGLBINDFRAMEBUFFER);
	INIT_OPENGL_FUNCTION(glFramebufferRenderbuffer, PFNGLFRAMEBUFFERRENDERBUFFER);
	INIT_OPENGL_FUNCTION(glFramebufferTexture, PFNGLFRAMEBUFFERTEXTURE);
	INIT_OPENGL_FUNCTION(glBindVertexArray, PFNGLBINDVERTEXARRAY);
	INIT_OPENGL_FUNCTION(glGenVertexArrays, PFNGLGENVERTEXARRAYS);
	INIT_OPENGL_FUNCTION(glDeleteVertexArrays, PFNGLDELETEVERTEXARRAYS);
	INIT_OPENGL_FUNCTION(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTER);
	INIT_OPENGL_FUNCTION(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAY);
	INIT_OPENGL_FUNCTION(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAY);
	INIT_OPENGL_FUNCTION(glVertexAttribDivisor, PFNGLVERTEXATTRIBDIVISOR);
	INIT_OPENGL_FUNCTION(glDrawArraysInstanced, PFNGLDRAWARRAYSINSTANCED);
	INIT_OPENGL_FUNCTION(glGenFramebuffers, PFNGLGENFRAMEBUFFERS);
	INIT_OPENGL_FUNCTION(glFramebufferTexture2D, PFNGLFRAMEBUFFERTEXTURE2D);
	INIT_OPENGL_FUNCTION(glGetShaderiv, PFNGLGETSHADERIV);
	INIT_OPENGL_FUNCTION(glGetShaderInfoLog, PFNGLGETSHADERINFOLOG);
	INIT_OPENGL_FUNCTION(glGetProgramiv, PFNGLGETPROGRAMIV);
	INIT_OPENGL_FUNCTION(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOG);
	INIT_OPENGL_FUNCTION(glDrawElementsInstanced, PFNGLDRAWELEMENTSINSTANCED);
	INIT_OPENGL_FUNCTION(glMapBuffer, PFNGLMAPBUFFER);
	INIT_OPENGL_FUNCTION(glUnmapBuffer, PFNGLUNMAPBUFFER);
	INIT_OPENGL_FUNCTION(glGetUniformLocation, PFNGLGETUNIFORMLOCATION);
	INIT_OPENGL_FUNCTION(glUniform1i, PFNGLUNIFORM1I);
	INIT_OPENGL_FUNCTION(glUniform1f, PFNGLUNIFORM1F);
	INIT_OPENGL_FUNCTION(glUniform1fv, PFNGLUNIFORM1FV);
	INIT_OPENGL_FUNCTION(glUniform2fv, PFNGLUNIFORM2FV);
	INIT_OPENGL_FUNCTION(glUniform3fv, PFNGLUNIFORM3FV);
	INIT_OPENGL_FUNCTION(glUniform4fv, PFNGLUNIFORM4FV);
	INIT_OPENGL_FUNCTION(glUniform1iv, PFNGLUNIFORM1IV);
	INIT_OPENGL_FUNCTION(glUniform2iv, PFNGLUNIFORM2IV);
	INIT_OPENGL_FUNCTION(glUniform3iv, PFNGLUNIFORM3IV);
	INIT_OPENGL_FUNCTION(glUniform4iv, PFNGLUNIFORM4IV);
	INIT_OPENGL_FUNCTION(glUniformMatrix3fv, PFNGLUNIFORMMATRIX3FV);
	INIT_OPENGL_FUNCTION(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FV);
	INIT_OPENGL_FUNCTION(glBindRenderbuffer, PFNGLBINDRENDERBUFFER);
	INIT_OPENGL_FUNCTION(glDeleteRenderbuffers, PFNGLDELETERENDERBUFFERS);
	INIT_OPENGL_FUNCTION(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERS);
	INIT_OPENGL_FUNCTION(glRenderbufferStorage, PFNGLRENDERBUFFERSTORAGE);
	INIT_OPENGL_FUNCTION(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUS);
	INIT_OPENGL_FUNCTION(glGenerateMipmap, PFNGLGENERATEMIPMAP);
	INIT_OPENGL_FUNCTION(glBlitFramebuffer, PFNGLBLITFRAMEBUFFER);
}
